// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtywt65AcL4q-h-IhiuRbewU_dVJM-5Z8',
    appId: '1:522702049030:web:5683598a02e2a201089887',
    messagingSenderId: '522702049030',
    projectId: 'quick-notes-4bb99',
    authDomain: 'quick-notes-4bb99.firebaseapp.com',
    storageBucket: 'quick-notes-4bb99.firebasestorage.app',
    measurementId: 'G-9JD9RFPQP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGOdlokNIa5o0pPYs_2t9tcj-pGmU2WjE',
    appId: '1:522702049030:android:807e116c1997a1b0089887',
    messagingSenderId: '522702049030',
    projectId: 'quick-notes-4bb99',
    storageBucket: 'quick-notes-4bb99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw9OvGY5f6bx6Et771nX31FHun3Pu0G_s',
    appId: '1:522702049030:ios:f10ba99ecb145b39089887',
    messagingSenderId: '522702049030',
    projectId: 'quick-notes-4bb99',
    storageBucket: 'quick-notes-4bb99.firebasestorage.app',
    iosBundleId: 'com.thequicknotes.flutterNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw9OvGY5f6bx6Et771nX31FHun3Pu0G_s',
    appId: '1:522702049030:ios:f10ba99ecb145b39089887',
    messagingSenderId: '522702049030',
    projectId: 'quick-notes-4bb99',
    storageBucket: 'quick-notes-4bb99.firebasestorage.app',
    iosBundleId: 'com.thequicknotes.flutterNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtywt65AcL4q-h-IhiuRbewU_dVJM-5Z8',
    appId: '1:522702049030:web:8b0cb7ebae07f217089887',
    messagingSenderId: '522702049030',
    projectId: 'quick-notes-4bb99',
    authDomain: 'quick-notes-4bb99.firebaseapp.com',
    storageBucket: 'quick-notes-4bb99.firebasestorage.app',
    measurementId: 'G-WY74TCR4LS',
  );
}
